### ISSUE TITLE
GuzzleHttp\Client service declaration in Symfony

### ISSUE THREAD

**Issue by albertemozo** [ideatosrl/instagram-feed#2]
I had to declare a service in order to meet the requirement of `app.instagram_feed`.

```
services:
    app.guzzle_client:
        class: GuzzleHttp\Client
```

I suppose this should be added to the docs.

**Comment by dymissy** [comment]
Depends on your project configuration, sometimes you already have a guzzle service. Anyway thanks for the tip, I'm going to add a section in the doc.
